/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuAdier;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
 



/**
 *
 * @author TSS
 */;
public class AdminPage extends javax.swing.JFrame {
   
    /**
     * Creates new form AdminPage
     */
    URL path;
    static JList Lname;
    String m;
    
    String url="jdbc:mysql://localhost:3306/studentaider?user=root&password=root";
    Connection conn;
    ResultSet res;
    String listName,selItem;
    static String selName;
    static int selNo;
    static JList aList;
    static String dfile[];
    DefaultListModel<String> model;
    JList list;
    moduleLists mol=new moduleLists();
    String fileName = selName,dbfile[]=new String[10];
    
    public AdminPage()
    {
        initComponents();
       display();
       path=moduleLists.class.getResource("/Java Basic Day5.pdf");
    }
    
    public AdminPage(String sel,int selIndex)
    {
        selName=sel;
        initComponents();
    }

   public AdminPage(String[] myfile)
    {
        dfile=myfile;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showPanel = new javax.swing.JPanel();
        clickPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblAll = new javax.swing.JLabel();
        lblYear1 = new javax.swing.JLabel();
        lblYear2 = new javax.swing.JLabel();
        lblYear3 = new javax.swing.JLabel();
        lblYear4 = new javax.swing.JLabel();
        lblYear5 = new javax.swing.JLabel();
        btnstuDelete = new javax.swing.JButton();
        btnstuAdd = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        btnPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(63, 229, 179));

        showPanel.setBackground(new java.awt.Color(102, 102, 102));
        showPanel.setForeground(new java.awt.Color(255, 255, 255));
        showPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        showPanel.setLayout(new java.awt.CardLayout());

        clickPanel.setBackground(new java.awt.Color(102, 0, 0));
        clickPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clickPanel.setForeground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(47, 46, 48));

        lblAll.setBackground(new java.awt.Color(47, 46, 48));
        lblAll.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblAll.setForeground(new java.awt.Color(204, 204, 255));
        lblAll.setText("  View All");
        lblAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAll, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAll, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblYear1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblYear1.setForeground(new java.awt.Color(204, 204, 204));
        lblYear1.setText("1st Year");
        lblYear1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0)));
        lblYear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYear1MouseClicked(evt);
            }
        });

        lblYear2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblYear2.setForeground(new java.awt.Color(204, 204, 204));
        lblYear2.setText("2nd Year");
        lblYear2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0)));
        lblYear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYear2MouseClicked(evt);
            }
        });

        lblYear3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblYear3.setForeground(new java.awt.Color(204, 204, 204));
        lblYear3.setText("3rd Year & H1");
        lblYear3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0)));
        lblYear3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYear3MouseClicked(evt);
            }
        });

        lblYear4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblYear4.setForeground(new java.awt.Color(204, 204, 204));
        lblYear4.setText("4th Year & H2");
        lblYear4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0)));
        lblYear4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYear4MouseClicked(evt);
            }
        });

        lblYear5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblYear5.setForeground(new java.awt.Color(204, 204, 204));
        lblYear5.setText("Q & H3");
        lblYear5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(102, 0, 0)));
        lblYear5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYear5MouseClicked(evt);
            }
        });

        btnstuDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnstuDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnstuDelete.setText("Delete Student");
        btnstuDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnstuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstuDeleteActionPerformed(evt);
            }
        });

        btnstuAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnstuAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnstuAdd.setText("Add Student");
        btnstuAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnstuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstuAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clickPanelLayout = new javax.swing.GroupLayout(clickPanel);
        clickPanel.setLayout(clickPanelLayout);
        clickPanelLayout.setHorizontalGroup(
            clickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clickPanelLayout.createSequentialGroup()
                .addGroup(clickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblYear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblYear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblYear3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblYear4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblYear5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(clickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnstuAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnstuDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        clickPanelLayout.setVerticalGroup(
            clickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clickPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblYear3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblYear4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblYear5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnstuAdd)
                .addGap(26, 26, 26)
                .addComponent(btnstuDelete)
                .addGap(48, 48, 48))
        );

        editPanel.setLayout(new java.awt.BorderLayout());

        btnPanel.setBackground(new java.awt.Color(47, 46, 48));

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clickPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(showPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(395, 395, 395)
                    .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(395, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(299, 299, 299)
                    .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(299, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(lblYear1.isEnabled())
            list=mol.year1Modules;
        else if(lblYear2.isEnabled())
            list=mol.year2Modules;
        myChooser mc;
        mc = new myChooser(list);
        mc=new myChooser(selItem);
        mc.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
        fileName=selName;
        System.out.println(fileName+" selected value");
       
        try{
            
            conn=DriverManager.getConnection(url);
            System.out.println("Get connected!");
            String query="delete from year1books where id like '%"+fileName+"%';";          
            Statement pstm=conn.createStatement();
            
            int r=pstm.executeUpdate(query);
            if(r>0)
            {
                JOptionPane.showMessageDialog(null,"Success");
            }      
            //done for database
            
            String query2="select id from year1books;";
                Statement stm=conn.createStatement();
                ResultSet res=stm.executeQuery(query2);
                
                for(int i=0;res.next();i++){
                    dbfile[i]=res.getString(1);
                    }
                    System.out.println("file retriving done.....");
                //********************
                    mol.year1Modules.setModel(new DefaultListModel());
                    model=(DefaultListModel)mol.year1Modules.getModel();
                    for(int j=0;j<dbfile.length-1;j++){
                    model.addElement(dbfile[j]);
                    }
                    mol.year1Modules.setModel(model);

                    for(int i=0;i<model.getSize();i++){
                     mol.year1Modules.setModel(model);
                    }

                    mol.year1Modules.setModel(model);
                    System.out.println(mol.year1Modules.getModel());
    }//GEN-LAST:event_btnDeleteActionPerformed
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    private void lblAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAllMouseClicked
            
            moduleLists ml=new moduleLists();
            btnPanel.setVisible(false);
   
            showPanel.removeAll();
            showPanel.add(ml.allModules);
           
            showPanel.updateUI();
            
    }//GEN-LAST:event_lblAllMouseClicked

    
    private void lblYear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYear1MouseClicked
           
           selItem=lblYear1.getText();
           System.out.println(selItem);
           
           myChooser mc=new myChooser(selItem);// for lblName to choose jlist to add fileName from myChooser add btn
           
           try{
                conn=DriverManager.getConnection(url);
                System.out.println("Get connected!");
                String query2="select id from year1books;";
                Statement stm=conn.createStatement();
                ResultSet res=stm.executeQuery(query2);
                
                for(int i=0;res.next();i++){
                    dbfile[i]=res.getString(1);
                    }
                    System.out.println("file retriving done.....");
                //********************
                    mol.year1Modules.setModel(new DefaultListModel());
                    model=(DefaultListModel)mol.year1Modules.getModel();
                    for(int j=0;j<dbfile.length;j++){
                    model.addElement(dbfile[j]);
                    }
                    mol.year1Modules.setModel(model);

                    for(int i=0;i<model.getSize();i++){
                     mol.year1Modules.setModel(model);
                    }

                    mol.year1Modules.setModel(model);
                    System.out.println(mol.year1Modules.getModel());
           }
           catch(Exception e)
           {
               e.printStackTrace();
           }
               
           
           editPanel.removeAll();
           showPanel.removeAll();
           btnPanel.setVisible(true);
               mol.year1Modules.validate();
               editPanel.add(mol.year1Modules,"Center");
               editPanel.add(btnPanel,"South");
               editPanel.validate();
               editPanel.updateUI();
               showPanel.add(editPanel);
               showPanel.updateUI();  
               
            
    }//GEN-LAST:event_lblYear1MouseClicked

    private void lblYear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYear2MouseClicked
           selItem=lblYear2.getText();
           System.out.println(selItem);
           showPanel.removeAll();
           editPanel.removeAll();
           btnPanel.setVisible(true);
               mol.year2Modules.validate();
               editPanel.add(mol.year2Modules,"Center");
               editPanel.add(btnPanel,"South");
               editPanel.validate();
               editPanel.updateUI();
               showPanel.add(editPanel);
               showPanel.updateUI();           
    }//GEN-LAST:event_lblYear2MouseClicked

    private void lblYear3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYear3MouseClicked
        selItem=lblYear3.getText();
        System.out.println(selItem);
        editPanel.removeAll();
        showPanel.removeAll();
        btnPanel.setVisible(true);
               mol.year3Modules.validate();
               editPanel.add(mol.year3Modules,"Center");
               editPanel.add(btnPanel,"South");
               editPanel.validate();
               editPanel.updateUI();
               showPanel.add(editPanel);
               showPanel.updateUI();
    }//GEN-LAST:event_lblYear3MouseClicked

    private void lblYear4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYear4MouseClicked
        selItem=lblYear4.getText();
        System.out.println(selItem);
        editPanel.removeAll();
        showPanel.removeAll();
        btnPanel.setVisible(true);
               mol.year4Modules.validate();
               editPanel.add(mol.year4Modules,"Center");
               editPanel.add(btnPanel,"South");
               editPanel.validate();
               editPanel.updateUI();
               showPanel.add(editPanel);
               showPanel.updateUI();
    }//GEN-LAST:event_lblYear4MouseClicked

    private void lblYear5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYear5MouseClicked
       selItem=lblYear5.getText();
        System.out.println(selItem);
        editPanel.removeAll();
        showPanel.removeAll();
        btnPanel.setVisible(true);
               mol.year5Modules.validate();
               editPanel.add(mol.year5Modules,"Center");
               editPanel.add(btnPanel,"South");
               editPanel.validate();
               editPanel.updateUI();
               showPanel.add(editPanel);
               showPanel.updateUI();
    }//GEN-LAST:event_lblYear5MouseClicked

    private void btnstuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstuDeleteActionPerformed
       newStudent stu=new newStudent();
       stu.txtName.setEditable(false);
       stu.cbnYear.setEnabled(false);
       stu.cbnrollno.setEnabled(false);
       stu.txtStudentID.setText("");
       stu.setVisible(true);
    }//GEN-LAST:event_btnstuDeleteActionPerformed

    private void btnstuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstuAddActionPerformed
       newStudent stu=new newStudent();
       stu.setVisible(true);
    }//GEN-LAST:event_btnstuAddActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        moduleLists ml=new moduleLists();
        selName=ml.selected;
        selNo=ml.selIndex;
        
        myChooser mc=new myChooser();
        dfile=mc.dbfile;
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage(selName,selNo).setVisible(true);
                new AdminPage(dfile).setVisible(true);
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnstuAdd;
    private javax.swing.JButton btnstuDelete;
    private javax.swing.JPanel clickPanel;
    public javax.swing.JPanel editPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAll;
    private javax.swing.JLabel lblYear1;
    private javax.swing.JLabel lblYear2;
    private javax.swing.JLabel lblYear3;
    private javax.swing.JLabel lblYear4;
    private javax.swing.JLabel lblYear5;
    public javax.swing.JPanel showPanel;
    // End of variables declaration//GEN-END:variables

    public void display() {
       moduleLists ml=new moduleLists();
            btnPanel.setVisible(false);
   
            showPanel.removeAll();
            showPanel.add(ml.allModules);
           
            showPanel.updateUI();
    }
}
