/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuAdier;

import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.print.attribute.Size2DSyntax;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author TSS
 */
public class myChooser extends javax.swing.JFrame {

    /**
     * Creates new form myChooser
     */
    URL pathModule;
    String lastElement;
    static String lblname;
    File folder;
    DefaultListModel model=new DefaultListModel();
    String  dbfile[]=new String[10];
                
    public static JList dlist;
    public static DefaultListModel dmodel;
    
    public myChooser() {
        
        
        initComponents();
    }
    
    public myChooser(String name)
    {
        lblname=name;
        initComponents();
    }
   
    public myChooser(JList list)
    {
        
        dlist=list;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        myChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        myChooser.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        myChooser.setApproveButtonText("Add");
        myChooser.setBackground(new java.awt.Color(102, 0, 0));
        myChooser.setControlButtonsAreShown(false);
        myChooser.setForeground(new java.awt.Color(204, 204, 204));
        myChooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                myChooserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        myChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(myChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String path,newPath;
        File file;
        StringTokenizer stk;
        Connection conn;
        Statement sta;
        String url="jdbc:mysql://localhost:3306/studentaider?user=root&password=root";
        file=myChooser.getSelectedFile();
        PreparedStatement ps=null;
        
        
        path=file.getAbsolutePath();
        System.out.println(path);
        
        try
        {
            lastElement=null;       
            byte pdfbyte[]=new byte[(int)file.length()];
            System.out.println(pdfbyte.length);
            DataInputStream dis=new DataInputStream(new FileInputStream(file));
            dis.readFully(pdfbyte);
            dis.close();
                       
            

            newPath=path.replace('/','\\');
            System.out.println(newPath);

            stk=new StringTokenizer(newPath, "\\");

                while (stk.hasMoreTokens())
                {
                    lastElement=stk.nextToken();
                }
                System.out.println(lastElement);

                conn=DriverManager.getConnection(url);
                System.out.println("get Connected!!");
                if(lblname.equals("1st Year")){
                ps=conn.prepareStatement("insert into year1books (id,Files) values (?,?);");
                }
                else if(lblname.equals("2nd Year"))
                {
                ps=conn.prepareStatement("insert into year2books (id,Files) values (?,?);");   
                }
                else if(lblname.equals("3rd Year & H1"))
                {
                ps=conn.prepareStatement("insert into year3books (id,Files) values (?,?);");   
                }
                else if(lblname.equals("4th Year & H2"))
                {
                ps=conn.prepareStatement("insert into year4books (id,Files) values (?,?);");   
                }
                else if(lblname.equals("Q & H3"))
                {
                ps=conn.prepareStatement("insert into year5books (id,Files) values (?,?);");   
                }
                ps.setString(1,lastElement);
                ps.setBytes(2,pdfbyte);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,pdfbyte.length);
                this.setVisible(false);
                
                //Done for database
              
                String query="select id from year1books;";
                Statement stm=conn.createStatement();
                ResultSet res=stm.executeQuery(query);
                
                for(int i=0;res.next();i++){
                    dbfile[i]=res.getString(1);
                    }
                    System.out.println("file retriving done.....");
                
                    //moduleLists mm=new moduleLists();
                
                AdminPage ap=new AdminPage(dbfile);
                
                moduleLists mm=new moduleLists();
                
                if(lblname.equals("1st Year")){
                      System.out.println("yarrrrrrrrrrrrrrrrrrrrrrrr");
                      
                      mm.year1Modules.setModel(new DefaultListModel());
                      dmodel=(DefaultListModel)mm.year1Modules.getModel();
                      for(int j=0;j<dbfile.length;j++){
                      dmodel.addElement(dbfile[j]);
                      }
                      dlist.setModel(dmodel);
                      
                      for(int i=0;i<dmodel.getSize();i++){
                       mm.year1Modules.setModel(dmodel);
                      }
                      
                     
                      System.out.println(lastElement);
                      System.out.println(dmodel.getSize());
                      System.out.println(dmodel);
                      mm.year1Modules.ensureIndexIsVisible(model.getSize());
                }
                /*else if(lblname.equals("2nd Year")){
                    model=(DefaultListModel)mm.year1Modules.getModel();
                      model.addElement(lastElement);
                      mm.year1Modules.setModel(model);
                      mm.allModules.setModel(model);
                      mm.year1Modules.updateUI();
                      mm.allModules.updateUI();
                }
                else if(lblname.equals("3rd Year & H1")){
                    model=(DefaultListModel)mm.year2Modules.getModel();
                    model.addElement(lastElement);
                    mm.year2Modules.setModel(model);
                    mm.allModules.setModel(model);
                    mm.year2Modules.updateUI();
                    mm.allModules.updateUI();
                }
                else if(lblname.equals("4th Year & H2")){
                    model=(DefaultListModel)mm.year3Modules.getModel();
                    model.addElement(lastElement);
                    mm.year3Modules.setModel(model);
                    mm.allModules.setModel(model);
                    mm.year3Modules.updateUI();
                    mm.allModules.updateUI();
                }
                else if(lblname.equals("Q & H3")){
                    model=(DefaultListModel)mm.year4Modules.getModel();
                    model.addElement(lastElement);
                    mm.year4Modules.setModel(model);
                    mm.allModules.setModel(model);
                    mm.year4Modules.updateUI();
                    mm.allModules.updateUI();
                    
                }
                else if(lblname.equals("")){
                    model=(DefaultListModel)mm.year5Modules.getModel();
                    model.addElement(lastElement);
                    mm.year5Modules.setModel(model);
                    mm.allModules.setModel(model);
                    mm.year5Modules.updateUI();
                    mm.allModules.updateUI();
                }*/
                System.out.println("successfull added to jlist ..... smileeeeeee");
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void myChooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_myChooserAncestorAdded
        // myChooser.setVisible(false);
    }//GEN-LAST:event_myChooserAncestorAdded

    private void myChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myChooserActionPerformed

    }//GEN-LAST:event_myChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        AdminPage ap=new AdminPage();
        lblname=ap.selItem;
        
        dmodel=ap.model;
        dlist=ap.list;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myChooser(lblname).setVisible(true);
                new myChooser(dlist).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JFileChooser myChooser;
    // End of variables declaration//GEN-END:variables
}
