/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stuAdier;

import java.awt.event.MouseListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;


/**
 *
 * @author TSS
 */

public class ReadPage extends javax.swing.JFrame{
    
    /**
     * Creates new form ReadPage
     */
    //JLabel lbl1,lbl2,lbl3,lbl4,lbl5;
    Connection conn;
    ResultSet res,res1;
    String url="jdbc:mysql://localhost:3306/studentaider?user=root&password=root";
    String year=null,checkID,rollNoDB;
    login login=new login();
    String stuID;
    static String id;
   
    public ReadPage(String id) {
        
         initComponents();
        //initComponentsCopy();
        stuID=id;
        
        display();
        
        try{
            conn=DriverManager.getConnection(url);
            System.out.println("get connected!!");
            PreparedStatement pstm1=conn.prepareStatement("select * from studentInfo where studentID=?");
            pstm1.setString(1,stuID);
            res1=pstm1.executeQuery();
            
            while(res1.next())
            {
                checkID=res1.getString("studentID");
                System.out.println(checkID);
            }
            
             if(stuID.equals(checkID))
            {
                String query3="select rollNo from studentInfo where studentID='"+checkID+"';";
                Statement stm=conn.createStatement();
                ResultSet res=stm.executeQuery(query3);
                
                while(res.next())
                {
                    rollNoDB=res.getString("rollNo");
                }
                System.out.println(rollNoDB);
                lblYear.setText(rollNoDB);
                lblYear.updateUI();
                
                setVisible(true);
                
             }
            else
                System.out.println("fail");
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblYear = new javax.swing.JLabel();
        lblAll = new javax.swing.JLabel();
        viewModules = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        lblYear.setBackground(new java.awt.Color(47, 46, 48));
        lblYear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblYear.setForeground(new java.awt.Color(204, 204, 255));
        lblYear.setText("  jLabel1");
        lblYear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 102)));
        lblYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYearMouseClicked(evt);
            }
        });

        lblAll.setBackground(new java.awt.Color(47, 46, 48));
        lblAll.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblAll.setForeground(new java.awt.Color(204, 204, 255));
        lblAll.setText("  All");
        lblAll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 102)));
        lblAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblYear, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
            .addComponent(lblAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAll, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 576));

        viewModules.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout viewModulesLayout = new javax.swing.GroupLayout(viewModules);
        viewModules.setLayout(viewModulesLayout);
        viewModulesLayout.setHorizontalGroup(
            viewModulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        viewModulesLayout.setVerticalGroup(
            viewModulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        getContentPane().add(viewModules, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAllMouseClicked
        viewModules.removeAll();

        display();
    }//GEN-LAST:event_lblAllMouseClicked

    private void lblYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblYearMouseClicked
        viewModules.removeAll();
        yearModule();
    }//GEN-LAST:event_lblYearMouseClicked
     
    public void display()
    {
        moduleLists ml=new moduleLists();
        
        viewModules.add(ml.allModules);
        viewModules.setVisible(true);
        viewModules.updateUI();
        
    }
 
    public void yearModule()
    {
        moduleLists ml=new moduleLists();
        String lblrno=lblYear.getText();
        if(lblrno.charAt(1)=='1' || lblrno.charAt(0)=='3')
        {
            viewModules.add(ml.year3Modules);
            viewModules.updateUI();
        }
        else if(lblrno.charAt(1)=='2' || lblrno.charAt(0)=='4')
        {
            viewModules.add(ml.year4Modules);
            viewModules.updateUI();
        }
        else if(lblrno.charAt(1)=='3' || lblrno.charAt(0)=='Q')
        {
            viewModules.add(ml.year5Modules);
            viewModules.updateUI();
        }
        else if(lblrno.charAt(0)=='1')
        {
            viewModules.add(ml.year1Modules);
            viewModules.updateUI();
        }
        else if(lblrno.charAt(0)=='2')
        {
            viewModules.add(ml.year2Modules);
            viewModules.updateUI();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"wrong Roll no...........");
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        login login=new login();
        id=login.sID;
        System.out.println(id+"oooooooo");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadPage(id).setVisible(true);
                
                   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAll;
    public javax.swing.JLabel lblYear;
    public javax.swing.JPanel viewModules;
    // End of variables declaration//GEN-END:variables
}
